Get ready for release 10.0.0

diff --git a/docker/Dockerfile-release b/docker/Dockerfile-release
--- a/docker/Dockerfile-release
+++ b/docker/Dockerfile-release
@@ -1,5 +1,5 @@
 # -*- Dockerfile -*-
-FROM ubuntu:24.10
+FROM ubuntu:26.04
 
 ENV MATHICS3_HOME=/home/ubuntu
 ENV MATHICS3_MODULE_OPTION="--load-module pymathics.graph,pymathics.natlang,pymathics.trepan"
@@ -26,10 +26,12 @@ RUN apt-get install -y -qq \
     asymptote \
     cargo \
     evince \
+    enchant-2 \
     gfortran \
     git \
     gyp \
     latexmk texlive-xetex \
+    libicu-dev \
     libffi-dev \
     liblapack-dev \
     libmysqlclient-dev \
@@ -38,8 +40,8 @@ RUN apt-get install -y -qq \
     libxcb-cursor-dev \
     libxml2-dev \
     libxslt1-dev \
-    llvm-15 \
-    llvm-15-dev \
+    llvm-18 \
+    llvm-18-dev \
     lmodern texlive-latex-extra \
     maria \
     mesa-utils \
@@ -48,8 +50,7 @@ RUN apt-get install -y -qq \
     pkg-config \
     pyqt5-dev-tools \
     python3-pip \
-    python3.13-dev \
-    python3.13-venv \
+    python3.14-venv \
     remake \
     rustc \
     sqlite3 \
@@ -62,43 +63,128 @@ RUN apt-get install -y -qq \
 # # defer deletion until close to the end
 # # RUN rm -fr /tmp*_amd64.deb
 
-RUN /usr/bin/python3.13 -m venv /opt/python3.13
-ENV PATH=.:/opt/python3.13/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
-ENV PYTHON=/opt/python3.13/bin/python3.13
-ENV PIP=/opt/python3.13/bin/pip
+RUN /usr/bin/python3.14 -m venv /opt/python3.14
+ENV PATH=.:/opt/python3.14/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ENV PYTHON=/opt/python3.14/bin/python3.14
+ENV PIP=/opt/python3.14/bin/pip
 RUN $PYTHON -m pip install --upgrade pip
 
-####################
-# Our hacked stopit
-####################
+#########################
+# Development libraries
+#########################
 
-RUN git clone --depth 1 https://github.com/Mathics3/stopit.git
-RUN (cd stopit && $PIP install -e .)
+RUN $PYTHON -m pip install setuptools
+RUN $PIP install --local --no-build-isolation -e git+https://github.com/rocky/python-filecache.git#egg=pyficache
+RUN $PIP install --local -e git+https://github.com/rocky/python-uncompyle6.git#egg=uncompyle6
+RUN $PIP install --local -e git+https://github.com/rocky/python-decompile3.git#egg=decompyle3
+RUN $PIP install git+https://github.com/rocky/python-filecache#egg=pyficache
+RUN $PIP install -e git+https://github.com/Trepan-Debuggers/python3-trepan#egg=trepan3k
+# RUN git clone --depth 1 https://github.com/Mathics3/Mathics3-scanner.git
+# RUN (cd Mathics3-scanner && $PIP install -e .[full] && bash -x ./admin-tools/make-JSON-tables.sh)
+# RUN $PIP install git+https://github.com/Trepan-Debuggers/python3-trepan.git
+RUN $PIP install Mathics3-scanner
 
-COPY src/doc_html_data.pcl doc_html_data.pcl
-RUN mkdir -p ${MATHICS3_HOME}/.local/var/Mathics3
-RUN mv -v doc_html_data.pcl ${MATHICS3_HOME}/.local/var/Mathics3/doc_data_html.pcl
-RUN mkdir -p ${MATHICS3_HOME}/mathics-core/mathics/doc/latex
-COPY src/mathics.pdf mathics-core/mathics/doc/latex/mathics.pdf
+# #################
+# # Mathics3 core #
+# #################
 
-RUN $PIP install cython Mathics3[full]
-RUN $PIP install PyQt6
-RUN $PIP install mathicsscript[full]
-RUN $PIP install Mathics-Django[full]
-RUN $PIP install Mathics3-graph
-RUN $PIP install Mathics3-Module-PyICU
-RUN $PIP install Mathics3-Module-trepan
-RUN $PIP install trepan3k-mathics3
+RUN $PIP install Mathics3
+# RUN git clone --depth 1 https://github.com/Mathics3/mathics-core.git
+# For reasons I don't understand, "submodule init" only adds the first repository.
+# We need to add the second repository Rubi, explicitly
+# RUN (cd mathics-core && git submodule update --init --recursive && \
+#     git submodule add https://github.com/Mathics3/Mathics3-Rubi.git mathics/Packages/Rubi)
+# RUN (cd mathics-core && git submodule && $PIP install -e .[full,cython] --no-build-isolation)
+# RUN (cd mathics-core && bash ./admin-tools/make-JSON-tables.sh)
+
+##############################################
+# Mathics Modules: Trepan, Networkx, and NLTK
+##############################################
+# RUN git clone --depth 1 https://github.com/Mathics3/Mathics3-pygments.git
+# RUN (cd Mathics3-pygments && $PIP install -e . --no-build-isolation)
+
+# Not sure why this is needed and not pulled in from Mathics3-trepan automatically...
+RUN $PIP install Mathics3-pygments Mathics3-Module-Base
+
+RUN git clone --depth 1 https://github.com/Mathics3/Mathics3-trepan.git
+RUN (cd Mathics3-trepan && $PIP install --no-build-isolation -e .)
+
+RUN git clone --depth 1 https://github.com/Mathics3/trepan3k-mathics-debugger/
+RUN (cd trepan3k-mathics-debugger && $PIP install -e .)
+
+# RUN $PIP install --no-build-isolation -e "git+https://github.com/Mathics3/Mathics3-Module-networkx#egg=Mathics3-Module-networkx"
+# RUN $PIP install --no-build-isolation -e "git+https://github.com/Mathics3/Mathics3-Module-nltk#egg=Mathics3-Module-nltk"
+# RUN $PIP install --no-build-isolation -e "git+https://github.com/Mathics3/Mathics3-Module-PyICU#egg=Mathics3-Module-PyICU"
 
 RUN $PIP install spacy wordcloud
 RUN $PYTHON -m spacy download en_core_web_md
 RUN $PIP install nltk
-RUN $PIP install Mathics3-Module-nltk
+RUN $PIP install Mathics3-Module-nltk Mathics3-Module-networkx Mathics3-Module-PyICU
+
+#######################
+# LaTeX/PDF generation
+#######################
+# This has to appear after core and Mathics3 Modules have been built.
+# Making the PDF is very time consuming. For now its is easy to build outside of
+# docker and just copy in.
+
+# RUN (cd mathics-core/mathics/doc/latex && PYTHON=$PYTHON make mathics.pdf) || /bin/true
+# COPY tex-images/*.pdf mathics-core/mathics/doc/latex/
+# ENV DOC_LATEX_FILE=/usr/src/app/mathics-core/mathics/doc/latex/documentation.tex
+# # COPY src/documentation.tex mathics-core/mathics/doc/latex/documentation.tex
+# # COPY src/version-info.tex mathics-core/mathics/doc/latex/
+
+COPY src/mathics3.pdf mathics-core/mathics/doc/latex/mathics3.pdf
+
+###################
+# Mathics3 Django #
+###################
+RUN mkdir -p ${MATHICS3_HOME}/.local/var/Mathics3/
+RUN $PIP install mathics3-django
+
+# RUN git clone --depth 1 https://github.com/Mathics3/Mathics3-django.git
+# RUN (cd Mathics3-django && $PIP install -e .[full])
+# # Get threejs version created
+# RUN (cd Mathics3-django && make build)
+# # RUN $PYTHON -m pip install -e git+https://github.com/Mathics3/Mathics3-django#egg=Mathics3-Django[full]
+# # RUN $PYTHON -m pip install "Mathics-Django[full]>=7.0.0"
+# # RUN (cd src/Mathics3-django && PIP=$PIP make)
+# RUN (cd Mathics3-django && $PYTHON Mathics3_django/docpipeline.py -ok) || true
+# RUN (cd Mathics3-django && $PYTHON -m pip install --no-build-isolation -e .)
+# ENV DATA_DIR=/usr/src/app/mathics-core/mathics/doc/latex/
+# ENV DOCTEST_LATEX_DATA_PCL=/usr/src/app/mathics-core/mathics/doc/latex/doctext_latex_data.pcl
+ENV DOCTEST_USER_HTML_DATA_PATH=/home/ubuntu/Mathics3-django/mathics_django/doc_data_html.pcl
+COPY src/doc_html_data.pcl /home/ubuntu/Mathics3-django/mathics_django/doc_data_html.pcl
+
+##################
+# Mathicsscript  #
+##################
+
+# The below pulls in Mathics3-pygments
+RUN $PIP install mathicsscript
+# RUN git clone --depth 1 https://github.com/Mathics3/mathicsscript.git
+# RUN (cd mathicsscript && PYTHON=$PYTHON make install)
+
+# RUN (cd mathicsscript && $PYTHON -m pip install -e .[full])
+# RUN ${PYTHON} -m pip install -e git+https://github.com/Mathics3/mathicsscript#egg=mathicsscript[full]
+# RUN (cd src/mathicsscript && make)
+
+# ##################
+# # debug stuff    #
+# ##################
+# RUN apt-get install -y -qq emacs
+# RUN pip install trepan3k
+# RUN pip install remake
+
+##################
+# Finish up      #
+##################
+
+# Cleanup
+# RUN rm -fr /tmp*_amd64.deb /tmp/*.whl
 
 COPY entrypoint.sh /usr/local/bin/mathics3-omnibus.sh
 RUN chmod +x /usr/local/bin/mathics3-omnibus.sh
-COPY src/mathics.pdf mathics-core/mathics/doc/latex/mathics.pdf
-
 
 EXPOSE 8000
 
@@ -106,7 +192,7 @@ RUN mkdir -p ${MATHICS3_HOME}/.local
 RUN mkdir -p ${MATHICS3_HOME}/.config
 RUN mkdir -p ${MATHICS3_HOME}/data
 RUN mkdir -p ${MATHICS3_HOME}/.local/var/Mathics3/Packages
-COPY django-db/mathics.sqlite ${MATHICS3_HOME}/.local/var/Mathics3/mathics.sqlite
+COPY django-db/mathics3.sqlite ${MATHICS3_HOME}/.local/var/Mathics3/mathics3.sqlite
 RUN chown -R ubuntu:ubuntu $MATHICS3_HOME ${MATHICS3_HOME}/.local
 RUN chown -R ubuntu:ubuntu ${MATHICS3_HOME}/data
 USER ubuntu
