Lots of little changes for 10.0 release...
Mathics -> Mathics3 lots of places.

diff --git a/docker/Dockerfile-dev b/docker/Dockerfile-dev
--- a/docker/Dockerfile-dev
+++ b/docker/Dockerfile-dev
@@ -1,3 +1,4 @@
+# -*- Dockerfile -*-
 FROM ubuntu:25.04
 
 ENV MATHICS3_HOME=/home/ubuntu
@@ -66,26 +67,27 @@ ENV PYTHON=/opt/python3.13/bin/python3.13
 ENV PIP=/opt/python3.13/bin/pip
 RUN $PYTHON -m pip install --upgrade pip
 
-####################
-# Our hacked stopit
-####################
+#########################
+# Development libraries
+#########################
 
-RUN git clone --depth 1 https://github.com/Mathics3/stopit.git
-RUN (cd stopit && $PIP install -e .)
-
+RUN $PIP install --local -e git+https://github.com/rocky/python-xdis.git#egg=xdis
+RUN $PIP install --local --no-build-isolation -e git+https://github.com/rocky/python-filecache.git#egg=pyficache
+RUN $PIP install --local -e git+https://github.com/rocky/python-uncompyle6.git#egg=uncompyle6
+RUN $PIP install --local -e git+https://github.com/rocky/python-decompile3.git#egg=decompyle3
+RUN $PIP install git+https://github.com/rocky/python-filecache#egg=pyficache
 RUN $PIP install -e git+https://github.com/Trepan-Debuggers/python3-trepan#egg=trepan3k
-
-# ################
-# # Mathics core #
-# ################
-
-RUN git clone --depth 1 --branch release-2.0.0 https://github.com/Mathics3/mathics-scanner.git
-RUN (cd mathics-scanner && $PIP install -e .[full])
-RUN $PIP install cython
+RUN $PIP install -e git+https://github.com/Trepan-Debuggers/python3-trepan#egg=trepan3k
+RUN git clone --depth 1 https://github.com/Mathics3/Mathics3-scanner.git
+RUN (cd Mathics3-scanner && $PIP install -e .[full] && bash -x ./admin-tools/make-JSON-tables.sh)
 RUN $PIP install git+https://github.com/rocky/python-xdis.git
 RUN $PIP install git+https://github.com/Trepan-Debuggers/python3-trepan.git
 
-RUN git clone --depth 1 --branch release-9.0 https://github.com/Mathics3/mathics-core.git
+# #################
+# # Mathics3 core #
+# #################
+
+RUN git clone --depth 1 https://github.com/Mathics3/mathics-core.git
 # For reasons I don't understand, "submodule init" only adds the first repository.
 # We need to add the second repository Rubi, explicitly
 RUN (cd mathics-core && git submodule update --init --recursive && \
@@ -104,8 +106,8 @@ RUN (cd Mathics3-trepan && $PIP install --no-build-isolation -e .)
 RUN git clone --depth 1 https://github.com/Mathics3/trepan3k-mathics-debugger/
 RUN (cd trepan3k-mathics-debugger && $PIP install -e .)
 
-RUN $PIP install -e "git+https://github.com/Mathics3/pymathics-graph#egg=Mathics3-graph"
-RUN $PIP install -e "git+https://github.com/Mathics3/pymathics-natlang#egg=pymathics-natlang"
+RUN $PIP install --no-build-isolation -e "git+https://github.com/Mathics3/Mathics3-Module-networkx#egg=Mathics3-Module-networkx"
+RUN $PIP install --no-build-isolation -e "git+https://github.com/Mathics3/Mathics3-Module-nltk#egg=Mathics3-Module-nltk"
 
 RUN $PIP install spacy wordcloud
 RUN $PYTHON -m spacy download en_core_web_md
@@ -133,23 +135,23 @@ COPY src/mathics.pdf mathics-core/mathics/doc/latex/mathics.pdf
 ##################
 # Mathics Django #
 ##################
-RUN git clone --depth 1 https://github.com/Mathics3/mathics-django.git
-RUN (cd mathics-django && $PIP install -e .[full])
+RUN git clone --depth 1 https://github.com/Mathics3/Mathics3-django.git
+# RUN (cd Mathics3-django && $PIP install -e .[full])
 # # Get threejs version created
-RUN (cd mathics-django && make build)
-# # RUN $PYTHON -m pip install -e git+https://github.com/Mathics3/mathics-django#egg=Mathics-Django[full]
+RUN (cd Mathics3-django && make build)
+# # RUN $PYTHON -m pip install -e git+https://github.com/Mathics3/Mathics3-django#egg=Mathics3-Django[full]
 # # RUN $PYTHON -m pip install "Mathics-Django[full]>=7.0.0"
 
-# # RUN (cd src/mathics-django && PIP=$PIP make)
-# RUN (cd mathics-django && $PYTHON mathics_django/docpipeline.py -ok) || true
+# # RUN (cd src/Mathics3-django && PIP=$PIP make)
+# RUN (cd Mathics3-django && $PYTHON Mathics3_django/docpipeline.py -ok) || true
 COPY src/doc_html_data.pcl doc_html_data.pcl
-RUN mv -v doc_html_data.pcl /home/ubuntu/mathics-django/mathics_django/doc/doc_data_html.pcl
+RUN mv -v doc_html_data.pcl /home/ubuntu/Mathics3-django/mathics_django/doc/doc_data_html.pcl
 
 ##################
 # Mathicsscript  #
 ##################
 
-RUN git clone --depth 1 --branch release-9.0.0 https://github.com/Mathics3/mathicsscript.git
+RUN git clone --depth 1 https://github.com/Mathics3/mathicsscript.git
 RUN (cd mathicsscript && PYTHON=$PYTHON make install)
 
 RUN ${PYTHON} -m pip install mathicsscript[full]
@@ -163,11 +165,11 @@ RUN ${PYTHON} -m pip install mathicsscript[full]
 # RUN pip install trepan3k
 # # RUN pip install remake
 
-# ##################
-# # Finish up      #
-# ##################
+##################
+# Finish up      #
+##################
 
-# # Cleanup
+# Cleanup
 # RUN rm -fr /tmp*_amd64.deb /tmp/*.whl
 
 COPY entrypoint.sh /usr/local/bin/mathics-omnibus.sh
